/**
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.english.generator;

import com.google.inject.Inject;
import vary.pseudocodigo.dsl.c.generator.VaryGrammarGenerator;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class VaryGrammarEnglishGenerator extends VaryGrammarGenerator {
  @Inject
  public VaryGrammarEnglishGenerator() {
    super("English Messages");
  }
}
