/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.english.ui.contentassist

import vary.pseudocodigo.dsl.c.english.ui.contentassist.AbstractVaryGrammarEnglishProposalProvider
import vary.pseudocodigo.dsl.c.ui.contentassist.VaryGrammarProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VaryGrammarEnglishProposalProvider extends VaryGrammarProposalProvider {}
