/**
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.english.scoping;

import vary.pseudocodigo.dsl.c.scoping.VaryGrammarScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class VaryGrammarEnglishScopeProvider extends VaryGrammarScopeProvider {
}
