/*
* generated by Xtext
*/
package vary.pseudocodigo.dsl.c.english.ui.labeling

import com.google.inject.Inject
import vary.pseudocodigo.dsl.c.ui.labeling.VaryGrammarLabelProvider

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
class VaryGrammarEnglishLabelProvider extends VaryGrammarLabelProvider {

	@Inject
	new(org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider delegate) {
		super(delegate, "English");
	}
	
}
