/*
* generated by Xtext
*/
package vary.pseudocodigo.dsl.c.english.ui.outline

import vary.pseudocodigo.dsl.c.ui.outline.VaryGrammarOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class VaryGrammarEnglishOutlineTreeProvider extends VaryGrammarOutlineTreeProvider {
	
}
