/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.english.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import vary.pseudocodigo.dsl.c.english.ui.internal.VaryGrammarEnglishActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VaryGrammarEnglishExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VaryGrammarEnglishActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VaryGrammarEnglishActivator.getInstance().getInjector(VaryGrammarEnglishActivator.VARY_PSEUDOCODIGO_DSL_C_ENGLISH_VARYGRAMMARENGLISH);
	}
	
}
