/**
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.english.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import vary.pseudocodigo.dsl.c.ui.labeling.VaryGrammarLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class VaryGrammarEnglishLabelProvider extends VaryGrammarLabelProvider {
  @Inject
  public VaryGrammarEnglishLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate, "English");
  }
}
