/**
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.english.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class VaryGrammarEnglishDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
