<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diagramapseudocodigo" nsURI="http://diagramapseudocodigo/1.0"
    nsPrefix="diagramapseudocodigo">
  <eClassifiers xsi:type="ecore:EClass" name="Algoritmo" eSuperTypes="#//Codigo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inicio" lowerBound="1"
        eType="#//Inicio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subprocesos" upperBound="-1"
        eType="#//Subproceso" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantes" upperBound="-1"
        eType="#//Constante" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complejos" upperBound="-1"
        eType="#//TipoComplejo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comentarios" upperBound="-1"
        eType="#//Comentario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globales" upperBound="-1"
        eType="#//Declaracion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importaciones" upperBound="-1"
        eType="#//Modulo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inicio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentencias" upperBound="-1"
        eType="#//Sentencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaraciones" upperBound="-1"
        eType="#//Declaracion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sentencia" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaracionBasica" eSuperTypes="#//Declaracion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LlamadaFuncion" eSuperTypes="#//Valor #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operadores" upperBound="-1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableID" eSuperTypes="#//Operador #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mat" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="cadena"/>
  <eClassifiers xsi:type="ecore:EClass" name="CadenaCaracteres" eSuperTypes="#//Operador #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mat" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operador" abstract="true" eSuperTypes="#//Valor"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entero" eSuperTypes="#//Operador #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asignacion" eSuperTypes="#//Sentencia"/>
  <eClassifiers xsi:type="ecore:EClass" name="Escribir" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operador" lowerBound="1"
        upperBound="-1" eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Funcion" eSuperTypes="#//Subproceso">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devuelve" eType="#//Devolver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametro">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paso" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipo" lowerBound="1" eType="#//Tipo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Leer" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        upperBound="-1" eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Real" eSuperTypes="#//Operador #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Valor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operacion" eSuperTypes="#//Valor #//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EAttribute0rence0" eType="#//Operacion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negacionesFinales" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negacionesIniciales" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="signo">
    <eLiterals name="sum" literal="+"/>
    <eLiterals name="res" value="1" literal="-"/>
    <eLiterals name="mult" value="2" literal="*"/>
    <eLiterals name="div" value="3" literal="/"/>
    <eLiterals name="mayor" value="4" literal=">"/>
    <eLiterals name="menor" value="5" literal="&lt;"/>
    <eLiterals name="mayorigual" value="6" literal=">="/>
    <eLiterals name="menorigual" value="7" literal="&lt;="/>
    <eLiterals name="y" value="8"/>
    <eLiterals name="o" value="9"/>
    <eLiterals name="igualigual" value="10" literal="="/>
    <eLiterals name="distinto" value="11" literal="!="/>
    <eLiterals name="and" value="12"/>
    <eLiterals name="or" value="13"/>
    <eLiterals name="mod" value="14" literal="mod"/>
    <eLiterals name="div_real" value="15" literal="div"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Logico" eSuperTypes="#//Operador #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Si" eSuperTypes="#//Bloque">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sino" eType="#//Sino" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devuelve" eType="#//Devolver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sino">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentencias" upperBound="-1"
        eType="#//Sentencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devuelve" eType="#//Devolver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bloque" abstract="true" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" lowerBound="1" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentencias" upperBound="-1"
        eType="#//Sentencia" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mientras" eSuperTypes="#//Bloque"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repetir" eSuperTypes="#//Bloque"/>
  <eClassifiers xsi:type="ecore:EClass" name="Desde" eSuperTypes="#//Bloque">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asignacion" lowerBound="1"
        eType="#//AsignacionNormal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subproceso" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametros" upperBound="-1"
        eType="#//Parametro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentencias" upperBound="-1"
        eType="#//Sentencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaraciones" upperBound="-1"
        eType="#//Declaracion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedimiento" eSuperTypes="#//Subproceso"/>
  <eClassifiers xsi:type="ecore:EClass" name="Caracter" eSuperTypes="#//Operador #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncionInterna" eSuperTypes="#//Valor #//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operadores" upperBound="-1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segun" eSuperTypes="#//Bloque">
    <eStructuralFeatures xsi:type="ecore:EReference" name="casos" upperBound="-1"
        eType="#//Caso" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devuelve" eType="#//Devolver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Devolver">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Devolver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devuelve" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Caso">
    <eStructuralFeatures xsi:type="ecore:EReference" name="devuelve" eType="#//Devolver"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentencias" upperBound="-1"
        eType="#//Sentencia" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operador" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constante">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" lowerBound="1" eType="#//Operacion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vector" eSuperTypes="#//TipoComplejo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipo" lowerBound="1" eType="#//Tipo"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaracionDefinida" eSuperTypes="#//Declaracion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaracion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Matriz" eSuperTypes="#//TipoComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" upperBound="2" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipo" lowerBound="1" eType="#//Tipo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoComplejo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Registro" eSuperTypes="#//TipoComplejo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        upperBound="-1" eType="#//Declaracion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tipo"/>
  <eClassifiers xsi:type="ecore:EClass" name="TipoDefinido" eSuperTypes="#//Tipo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TipoBasico" eSuperTypes="#//Tipo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Archivo" eSuperTypes="#//TipoComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tipo" lowerBound="1" eType="#//Tipo"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerado" eSuperTypes="#//TipoComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor" lowerBound="1" upperBound="-1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subrango" eSuperTypes="#//TipoComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValorComplejo" eSuperTypes="#//Operador #//Sentencia #//Operacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValorRegistro" eSuperTypes="#//ValorComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre_registro" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campos" lowerBound="1"
        upperBound="-1" eType="#//CampoRegistro" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CampoRegistro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre_campo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//CampoRegistro"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primerIndice" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segundoIndice" eType="#//Operacion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValorVector" eSuperTypes="#//ValorComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre_vector" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campos" upperBound="-1"
        eType="#//CampoRegistro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indice" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValorMatriz" eSuperTypes="#//ValorComplejo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre_matriz" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campos" upperBound="-1"
        eType="#//CampoRegistro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primerIndice" lowerBound="1"
        eType="#//Operacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segundoIndice" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comentario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mensaje" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModoApertura">
    <eLiterals name="escritura"/>
    <eLiterals name="lectura" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncionFicheroAbrir" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modo" lowerBound="1" eType="#//ModoApertura"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="2"
        upperBound="2" eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuncionFicheroCerrar" eSuperTypes="#//Sentencia">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Suma" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resta" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicacion" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DivisionEntera" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparacion" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Igualdad" eSuperTypes="#//Operacion">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubrangoNumerico" eSuperTypes="#//Subrango">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limite_inf" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limite_sup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubrangoEnumerado" eSuperTypes="#//Subrango">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limite_inf" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limite_sup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsignacionNormal" eSuperTypes="#//Asignacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Mat" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valor_asignacion" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operador" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsignacionCompleja" eSuperTypes="#//Asignacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operador" lowerBound="1"
        eType="#//Operacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor_asignacion" lowerBound="1"
        eType="#//Operacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Codigo"/>
  <eClassifiers xsi:type="ecore:EClass" name="Modulo" eSuperTypes="#//Codigo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementacion" lowerBound="1"
        eType="#//Implementacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importaciones" upperBound="-1"
        eType="#//Modulo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exporta_globales" upperBound="-1"
        eType="#//Declaracion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exporta_tipos" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exporta_constantes" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exporta_subprocesos" upperBound="-1"
        eType="#//CabeceraSubproceso" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CabeceraSubproceso">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametros" upperBound="-1"
        eType="#//Parametro" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implementacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subprocesos" upperBound="-1"
        eType="#//Subproceso" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globales" upperBound="-1"
        eType="#//Declaracion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constantes" upperBound="-1"
        eType="#//Constante" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complejos" upperBound="-1"
        eType="#//TipoComplejo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CabeceraProcedimiento" eSuperTypes="#//CabeceraSubproceso"/>
  <eClassifiers xsi:type="ecore:EClass" name="CabeceraFuncion" eSuperTypes="#//CabeceraSubproceso">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipo" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mod" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DivisionReal" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperacionParentesis" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor_operacion" eType="#//Operacion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unaria" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Operacion"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signo_op" eType="#//signo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperacionCompleta" eSuperTypes="#//Operacion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valor_operacion" eType="#//Operacion"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
