/*
* generated by Xtext
*/
package vary.pseudocodigo.dsl.c.english;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VaryGrammarEnglishStandaloneSetup extends VaryGrammarEnglishStandaloneSetupGenerated{

	public static void doSetup() {
		new VaryGrammarEnglishStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

