/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;
import vary.pseudocodigo.dsl.c.scoping.VaryGrammarResourceDescriptionsStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VaryGrammarRuntimeModule extends vary.pseudocodigo.dsl.c.AbstractVaryGrammarRuntimeModule {
	
	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return VaryGrammarResourceDescriptionsStrategy.class;
	}
}
